FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/nginx.conf

# Virallinen Nginx Docker image Alpine Linux -pohjaisena. Haetaan vakaa versio Nginxistä.
# Tämä Dockerfile kopioi mukautetun nginx.conf-tiedoston Nginxin konfiguraatiokansioon, tarkalleen ottaen konttiin.
# Nginx toimii käänteisenä välityspalvelimena tässä esimerkkisovelluksessa.